version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env.local
    ports:
      - "5432:5432"
    networks:
      - my
    
networks:
  my:
    